export type AnonymousUserInfo = {
  userId: string;
  userToken: string;
};

export const anonymousUserInfo =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg1YWVkMjVlOTFhNTFjMDM2MTI1MWYiLCJ1c2VyVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlYMmxrSWpvaU5qWTROV0ZsWkRJMVpUa3hZVFV4WXpBek5qRXlOVEZtSW4wLjRtcnlreTdabExjNTVOWE8xVEpwZ2dsUGNFaU9iUmNOUXg1MVJ5WXdic0kifQ.860jJdbLOoEnY5A-R4ob__N0xgZGKTwCDzCI2w9FVdA";
