export default {
  APP_DRAWER: 'App Drawer',
  APP_TABS: 'App Tabs',
  AUTH: 'Auth',
  BOOKMARKS: 'Bookmarks',
  COMMENT: 'Comment',
  EXPLORE_NAVIGATOR: 'Explore Navigator',
  EXPLORE_TABS: 'Explore Tabs',
  FOLLOWERS: 'Followers',
  FOLLOWING: 'Following',
  HASHTAG: 'Hashtag',
  HASHTAGS_NAVIGATOR: 'Hashtags Navigator',
  HASHTAGS: 'Hashtags',
  HOME_NAVIGATOR: 'Home Navigator',
  LOGIN: 'Login',
  MENTIONS_NOTIFICATIONS: 'Mentions Notifications',
  MESSAGES_NAVIGATOR: 'Messages Navigator',
  NEW_PROJECT: 'New Project',
  NEW_SPARKLE: 'New Sparkle',
  NOTIFICATION_NAVIGATOR: 'Notification Navigator',
  NOTIFICATIONS_TABS: 'Notifications Tabs',
  NOTIFICATIONS: 'Notifications',
  PROFILE_NAVIGATOR: 'Profile Navigator',
  PROFILE_SETUP: 'profile setup',
  PROFILE_SPARKLES_AND_RESPARKLES: 'Profile Sparkles & Resparkles',
  PROFILE_UPDATE: 'Profile Update',
  PROFILE: 'Profile',
  PROJECTS: 'Projects',
  QUOTE: 'Quote',
  REGISTER: 'Register',
  THREAD: 'Thread',
  THEME_SETTINGS: 'Theme Setting',
  TIMELINE: 'Timeline',
  TIMELINE_TAB: 'Timeline Tab',
  USERS_NAVIGATOR: 'Users Navigator',
  USERS: 'Users',
  VIEW_IMAGE: 'View Image',
  FEEDBACK:'feedback',
} as const;
