export default {
  AUTH: "Auth",
  EXPLORE_NAVIGATOR: "Explore Navigator",
  FOLLOWERS: "Followers",
  FOLLOWING: "Following",
  HOME_NAVIGATOR: "Home Navigator",
  MESSAGES_NAVIGATOR: "Messages Navigator",
  NOTIFICATION_NAVIGATOR: "Notification Navigator",
  PROFILE: "Profile",
  PROFILE_SPARKLES: "Profile Sparkles",
  PROFILE_SPARKLES_AND_RESPARKLES: "Profile Sparkles & Resparkles",
  PROFILE_MEDIA: "Profile Media",
  PROFILE_NAVIGATOR: "Profile Navigator",
  THREAD: "Thread",
  TIMELINE: "Timeline",
  USERS: "Users",
} as const;
